// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: proto/trackers.proto

package trackers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTrackersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTrackersRequest) Reset() {
	*x = GetTrackersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_trackers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTrackersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackersRequest) ProtoMessage() {}

func (x *GetTrackersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trackers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackersRequest.ProtoReflect.Descriptor instead.
func (*GetTrackersRequest) Descriptor() ([]byte, []int) {
	return file_proto_trackers_proto_rawDescGZIP(), []int{0}
}

func (x *GetTrackersRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTrackersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trackers string `protobuf:"bytes,1,opt,name=trackers,proto3" json:"trackers,omitempty"`
}

func (x *GetTrackersResponse) Reset() {
	*x = GetTrackersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_trackers_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTrackersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackersResponse) ProtoMessage() {}

func (x *GetTrackersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trackers_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackersResponse.ProtoReflect.Descriptor instead.
func (*GetTrackersResponse) Descriptor() ([]byte, []int) {
	return file_proto_trackers_proto_rawDescGZIP(), []int{1}
}

func (x *GetTrackersResponse) GetTrackers() string {
	if x != nil {
		return x.Trackers
	}
	return ""
}

var File_proto_trackers_proto protoreflect.FileDescriptor

var file_proto_trackers_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x73,
	0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x31, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x32, 0x57, 0x0a, 0x07, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x65, 0x72, 0x12, 0x4c, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b,
	0x65, 0x72, 0x73, 0x12, 0x1c, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c,
	0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x2f, 0x74,
	0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_trackers_proto_rawDescOnce sync.Once
	file_proto_trackers_proto_rawDescData = file_proto_trackers_proto_rawDesc
)

func file_proto_trackers_proto_rawDescGZIP() []byte {
	file_proto_trackers_proto_rawDescOnce.Do(func() {
		file_proto_trackers_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_trackers_proto_rawDescData)
	})
	return file_proto_trackers_proto_rawDescData
}

var file_proto_trackers_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_trackers_proto_goTypes = []interface{}{
	(*GetTrackersRequest)(nil),  // 0: trackers.GetTrackersRequest
	(*GetTrackersResponse)(nil), // 1: trackers.GetTrackersResponse
}
var file_proto_trackers_proto_depIdxs = []int32{
	0, // 0: trackers.Tracker.GetTrackers:input_type -> trackers.GetTrackersRequest
	1, // 1: trackers.Tracker.GetTrackers:output_type -> trackers.GetTrackersResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_trackers_proto_init() }
func file_proto_trackers_proto_init() {
	if File_proto_trackers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_trackers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTrackersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_trackers_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTrackersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_trackers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_trackers_proto_goTypes,
		DependencyIndexes: file_proto_trackers_proto_depIdxs,
		MessageInfos:      file_proto_trackers_proto_msgTypes,
	}.Build()
	File_proto_trackers_proto = out.File
	file_proto_trackers_proto_rawDesc = nil
	file_proto_trackers_proto_goTypes = nil
	file_proto_trackers_proto_depIdxs = nil
}
