name: main

on:
  push:
    branches: [ main, dev ]
    paths:
      - './**'
  pull_request:
    branches: [ main, dev ]
    paths:
      - './**'
    types: [ opened, edited, synchronize, reopened ]

defaults:
  run:
    working-directory: './server'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        env:
          GO_VERSION: 1.19
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        env:
          GOLANGCI-LINT_VERSION: v1.50.0
        with:
          skip-go-installation: true
          version: ${{ env.GOLANGCI-LINT_VERSION }}
          working-directory: './'